spring.application.name=app


#database configuration : mysql
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=${DB_DataSource}

# hibernate configuration
spring.jpa.hibernate.ddl-auto=${DB_DDL}


